controllers/producto_controller.py
from flask import request, redirect, url_for, Blueprint

from models.producto_model import Producto
from views import producto_view

producto_bp = Blueprint('producto', __name__, url_prefix='/productos')

@producto_bp.route('/')
def index():
    #Recupera todos los regustros de productos
    productos = Producto.get_all()
    return producto_view.list(productos)

@producto_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        descripcion = request.form['descripcion']
        precio = request.form['precio']
        stock = request.form['stock']

        producto = Producto(descripcion, precio, stock)
        producto.save()
        return redirect(url_for('producto.index'))
    
    return producto_view.create()

@producto_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    producto = Producto.get_by_id(id)
    if request.method == 'POST':
        descripcion = request.form['descripcion']
        precio = request.form['precio']
        stock = request.form['stock']
        #Actualiza el producto
        producto.update(descripcion=descripcion, precio=precio, stock=stock)
        return redirect(url_for('producto.index'))
    
    return producto_view.edit(producto)

@producto_bp.route('/delete/<int:id>')
def delete(id):        
    producto = Producto.get_by_id(id)
    producto.delete()
    return redirect(url_for('producto.index'))

views/producto_view.py
from flask import render_template

def list(productos):
    return render_template('productos/index.html',productos=productos)

def create():
    return render_template('productos/create.html')

def edit(producto):
    return render_template('productos/edit.html', producto=producto)

templates/productos/create.html
{% extends('base.html') %}

{% block title %} PRODUCTOS | CREATE {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Registro de Producto
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('producto.create') }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-card-text me-2"></i>Descripcion</label>
                    <input type="text" class="form-control" name="descripcion" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-currency-dollar me-2"></i>
                        Precio</label>
                    <input type="number" class="form-control" name="precio" min="0" step="0.01" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-box-seam me-2"></i>Cantidad</label>
                    <input type="number" class="form-control" name="stock" required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Registrar Producto
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/productos/edit.html
{% extends('base.html') %}

{% block title %} PRODUCTOS | EDITAR {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Actualizacion de Producto
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('producto.edit',id=producto.id) }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-card-text me-2"></i>Descripcion</label>
                    <input type="text" class="form-control" name="descripcion" value="{{producto.descripcion}}"
                        required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-currency-dollar me-2"></i>
                        Precio</label>
                    <input type="number" class="form-control" name="precio" min="0" step="0.01"
                        value="{{producto.precio}}" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-box-seam me-2"></i>Cantidad</label>
                    <input type="number" class="form-control" name="stock" value="{{producto.stock}}" required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Actualizar Producto
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/productos/index.html
{% extends 'base.html' %}

{% block title %} PRODUCTOS {% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4 mt-4">
        <h2 class="fw-bold text-dark">
            <i class="bi bi-journal-text me-2"></i>Lista de Productos
        </h2>
        <a href="{{ url_for('producto.create') }}" class="btn btn-success ">
            <i class="bi bi-plus-circle me-1"></i> Nuevo Producto
        </a>
    </div>

<table class="table table-hover align-middle shadow-sm rounded overflow-hidden">
    <thead class="table-dark border-1">
        <tr>
            <th>ID</th>
            <th>Descripcion</th>
            <th>Precio</th>
            <th>Stock</th>
            <th></th>
        </tr>
    </thead>
    <tbody class="border-1">
        {% for item in productos %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.descripcion}}</td>
            <td>{{item.precio | round(2)}}</td>
            <td>{{item.stock}}</td>

            <td class="text-center">
                <a href="{{url_for('producto.edit',id=item.id)}}" class="btn btn-sm btn-warning me-4" title="Editar">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{{url_for('producto.delete',id=item.id)}}" class="btn btn-sm btn-danger " title="Eliminar"
                    onclick="return confirm('¿Estás seguro de eliminar este producto?');">
                    <i class="bi bi-trash-fill"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>



{% endblock %}