controllers/usuario_controller.py
from flask import request, redirect, url_for, Blueprint

from models.usuario_model import Usuario
from views import usuario_view

usuario_bp = Blueprint('usuario', __name__, url_prefix='/usuarios')

@usuario_bp.route('/')
def index():
    #Recupera todos los regustros de usuarios
    usuarios = Usuario.get_all()
    return usuario_view.list(usuarios)

@usuario_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']

        usuario = Usuario(nombre, username, password, rol)
        usuario.save()
        return redirect(url_for('usuario.index'))
    
    return usuario_view.create()

@usuario_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    usuario = Usuario.get_by_id(id)
    if request.method == 'POST':
        nombre = request.form['nombre']
        username = request.form['username']
        password = request.form['password']
        rol = request.form['rol']
        #Actualiza el usuario
        usuario.update(nombre=nombre, username=username, password=password, rol=rol)
        return redirect(url_for('usuario.index'))
    
    return usuario_view.edit(usuario)

@usuario_bp.route('/delete/<int:id>')
def delete(id):        
    usuario = Usuario.get_by_id(id)
    usuario.delete()
    return redirect(url_for('usuario.index'))

views/usuario_view.py
from flask import render_template

def list(usuarios):
    return render_template('usuarios/index.html',usuarios=usuarios)

def create():
    return render_template('usuarios/create.html')

def edit(usuario):
    return render_template('usuarios/edit.html', usuario=usuario)

templates/usuarios/create.html
{% extends('base.html') %}

{% block title %} USUARIOS | CREATE {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Registro de Usuario
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('usuario.create') }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person-lines-fill me-2"></i>Nombre</label>
                    <input type="text" class="form-control" name="nombre" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-person-circle me-2"></i>Username</label>
                    <input type="text" class="form-control" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-lock-fill me-2"></i>Password</label>
                    <input type="password" class="form-control" name="password" required>
                </div>
                <div class="mb-3">
                    <label for="rol" class="form-label"><i class="bi bi-person-vcard me-2"></i>Rol</label>
                    <select class="form-select" name="rol" required>
                        <option value="admin">Administrador</option>
                        <option value="cajero">Cajero</option>
                    </select>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Registrar Usuario
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/usuarios/edit.html
{% extends('base.html') %}

{% block title %} USUARIOS | EDITAR {% endblock %}

{% block content %}

<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Actualizar Usuario
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('usuario.edit',id=usuario.id) }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person-lines-fill me-2"></i>Nombre</label>
                    <input type="text" class="form-control" name="nombre" value="{{usuario.nombre}}" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-person-circle me-2"></i>Username</label>
                    <input type="text" class="form-control" name="username" value="{{usuario.username}}" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-lock-fill me-2"></i>Password</label>
                    <input type="password" class="form-control" name="password">
                </div>
                <div class="mb-3">
                    <label for="rol" class="form-label"><i class="bi bi-person-vcard me-2"></i>Rol</label>
                    <select class="form-select" name="rol" required>
                        <option value="admin" {% if usuario.rol=='admin' %} selected {% endif %}>Administrador</option>
                        <option value="cajero" {% if usuario.rol=='cajero' %} selected {% endif %}>Cajero</option>
                    </select>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Actualizar Usuario
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/usuarios/index.html
{% extends 'base.html' %}

{% block title %} USUARIOS {% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4 mt-4">
        <h2 class="fw-bold text-dark">
            <i class="bi bi-journal-text me-2"></i>Lista de Usuarios
        </h2>
        <a href="{{ url_for('usuario.create') }}" class="btn btn-success ">
            <i class="bi bi-plus-circle me-1"></i> Nuevo Usuario
        </a>
    </div>

<table class="table table-hover align-middle shadow-sm rounded overflow-hidden">
    <thead class="table-dark border-1">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Username</th>
            <th>Rol</th>
            <th></th>
            
        </tr>
    </thead>
    <tbody class="border-1">
        {% for user in usuarios %}
        <tr>
            <td>{{user.id}}</td>
            <td>{{user.nombre}}</td>
            <td>{{user.username}}</td>
            <td>{{user.rol}}</td>

            <td class="text-center">
                <a href="{{url_for('usuario.edit',id=user.id)}}" class="btn btn-sm btn-warning me-4" title="Editar">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{{url_for('usuario.delete',id=user.id)}}" class="btn btn-sm btn-danger " title="Eliminar"
                    onclick="return confirm('¿Estás seguro de eliminar este usuario?');">
                    <i class="bi bi-trash-fill"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>



{% endblock %}