controllers/venta_controller.py
from flask import request, redirect, url_for, Blueprint
from datetime import datetime

from models.venta_model import Venta
from models.cliente_model import Cliente
from models.producto_model import Producto

from views import venta_view

venta_bp = Blueprint('venta', __name__, url_prefix='/ventas')

@venta_bp.route('/')
def index():
    #Recupera todos los regustros de ventas
    ventas = Venta.get_all()
    return venta_view.list(ventas)

@venta_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        cliente_id = request.form['cliente_id']
        producto_id = request.form['producto_id']
        cantidad = request.form['cantidad']
        fecha_str = request.form['fecha']
        #Convertir fecha a datetime
        fecha = datetime.strptime(fecha_str, '%Y-%m-%d').date()

        venta = Venta(cliente_id = cliente_id, producto_id=producto_id, cantidad=cantidad, fecha=fecha)
        venta.save()
        return redirect(url_for('venta.index'))
    
    clientes = Cliente.query.all()
    productos = Producto.query.all()
    return venta_view.create(clientes, productos)
    
  

@venta_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    venta = Venta.get_by_id(id)
    if request.method == 'POST':
        cliente_id = request.form['cliente_id']
        producto_id = request.form['producto_id']
        cantidad = request.form['cantidad']
        fecha_str = request.form['fecha']
        #Convertir fecha a datetime
        fecha = datetime.strptime(fecha_str, '%Y-%m-%d').date()
        
        #Actualiza el venta
        venta.update(cliente_id=cliente_id, producto_id=producto_id, cantidad=cantidad, fecha=fecha)
        return redirect(url_for('venta.index'))
    
    clientes = Cliente.query.all()
    productos = Producto.query.all()
    
    return venta_view.edit(venta, clientes, productos)

@venta_bp.route('/delete/<int:id>')
def delete(id):        
    venta = Venta.get_by_id(id)
    venta.delete()
    return redirect(url_for('venta.index'))

views/venta_view.py
from flask import render_template

def list(ventas):
    return render_template('ventas/index.html',ventas=ventas)

def create(clientes, productos):
    # se requiere productos y clientes para crear una venta
    return render_template('ventas/create.html', clientes=clientes, productos=productos)

def edit(venta, clientes, productos):
     # se requiere productos y clientes para crear una venta
    return render_template('ventas/edit.html', venta=venta, clientes=clientes, productos=productos)

templates/ventas/create.html
{% extends('base.html') %}

{% block title %} VENTAS | CREATE {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Registro de Venta
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('venta.create') }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person me-2"></i>Cliente</label>
                    <select class="form-select" name="cliente_id" required>
                        <option value="">Seleccione un cliente</option>
                        {% for cliente in clientes %}
                        <option value="{{cliente.id}}">{{cliente.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-bag me-2"></i>Producto</label>
                    <select class="form-select" name="producto_id" required>
                        <option value="">Seleccione un producto</option>
                        {% for producto in productos %}
                        <option value="{{producto.id}}">{{producto.descripcion}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-box-seam me-2"></i>Cantidad</label>
                    <input type="number" class="form-control" name="cantidad"  required>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-calendar2-date me-2"></i>Fecha</label>
                    <input type="date" class="form-control" name="fecha"  required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Registrar Venta
                    </button>
                </div>
               
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/ventas/edit.html
{% extends('base.html') %}

{% block title %} VENTAS | EDITAR {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Actualizacion de Venta
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('venta.edit',id=venta.id) }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person me-2"></i>Cliente</label>
                    <select class="form-select" name="cliente_id" required>
                        <option value="">Seleccione un cliente</option>
                        {% for cliente in clientes %}
                        <option value="{{cliente.id}}" {% if venta.cliente_id==cliente.id %} selected {% endif %}>
                            {{cliente.nombre}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-bag me-2"></i>Producto</label>
                    <select class="form-select" name="producto_id" required>
                        <option value="">Seleccione un producto</option>
                        {% for producto in productos %}
                        <option value="{{producto.id}}" {% if venta.producto_id==producto.id %} selected {% endif %}>
                            {{producto.descripcion}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-box-seam me-2"></i>Cantidad</label>
                    <input type="number" class="form-control" name="cantidad" value="{{venta.cantidad}}" required>
                </div>
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-calendar2-date me-2"></i>Fecha</label>
                    <input type="date" class="form-control" name="fecha" value="{{venta.fecha.strftime('%Y-%m-%d')}}" required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Actualizar Venta
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/ventas/index.html
{% extends 'base.html' %}

{% block title %} VENTAS {% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4 mt-4">
        <h2 class="fw-bold text-dark">
            <i class="bi bi-journal-text me-2"></i>Lista de Ventas
        </h2>
        <a href="{{ url_for('venta.create') }}" class="btn btn-success ">
            <i class="bi bi-plus-circle me-1"></i> Nuevo Producto
        </a>
    </div>

<table class="table table-hover align-middle shadow-sm rounded overflow-hidden">
    <thead class="table-dark border-1">
        <tr>
            <th>ID</th>
            <th>Cliente</th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Fecha</th>
            <th></th>
        </tr>
    </thead>
    <tbody class="border-1">
        {% for item in ventas %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.cliente.nombre}}</td>
            <td>{{item.producto.descripcion}}</td>
            <td>{{item.cantidad}}</td>
            <td>{{item.fecha.strftime('%d/%m/%Y')}}</td>

            <td class="text-center">
                <a href="{{url_for('venta.edit',id=item.id)}}" class="btn btn-sm btn-warning me-4" title="Editar">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{{url_for('venta.delete',id=item.id)}}" class="btn btn-sm btn-danger " title="Eliminar"
                    onclick="return confirm('¿Estás seguro de eliminar esta venta?');">
                    <i class="bi bi-trash-fill"></i>
                </a>
            </td>
            
        </tr>
        {% endfor %}
    </tbody>

</table>



{% endblock %}