controllers/cliente_controller.py
from flask import request, redirect, url_for, Blueprint

from models.cliente_model import Cliente
from views import cliente_view

cliente_bp = Blueprint('cliente', __name__, url_prefix='/clientes')

@cliente_bp.route('/')
def index():
    #Recupera todos los regustros de clientes
    clientes = Cliente.get_all()
    return cliente_view.list(clientes)

@cliente_bp.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        nombre = request.form['nombre']
        email = request.form['email']
        telefono = request.form['telefono']

        cliente = Cliente(nombre, email, telefono)
        cliente.save()
        return redirect(url_for('cliente.index'))
    
    return cliente_view.create()

@cliente_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):
    cliente = Cliente.get_by_id(id)
    if request.method == 'POST':
        nombre = request.form['nombre']
        email = request.form['email']
        telefono = request.form['telefono']
        #Actualiza el cliente
        cliente.update(nombre=nombre, email=email, telefono=telefono)
        return redirect(url_for('cliente.index'))
    
    return cliente_view.edit(cliente)

@cliente_bp.route('/delete/<int:id>')
def delete(id):        
    cliente = Cliente.get_by_id(id)
    cliente.delete()
    return redirect(url_for('cliente.index'))

views/cliente_view.py
from flask import render_template

def list(clientes):
    return render_template('clientes/index.html',clientes=clientes)

def create():
    return render_template('clientes/create.html')

def edit(cliente):
    return render_template('clientes/edit.html', cliente=cliente)

templates/clientes/create.html
{% extends('base.html') %}

{% block title %} CLIENTES | CREATE {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Registro de Cliente
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('cliente.create') }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person-lines-fill me-2"></i>Nombre</label>
                    <input type="text" class="form-control" name="nombre" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-envelope-at me-2"></i>Correo electrónico</label>
                    <input type="text" class="form-control" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-telephone-fill me-2"></i>Telefono</label>
                    <input type="number" class="form-control" name="telefono" required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Registrar Cliente
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/clientes/edit.html
{% extends('base.html') %}

{% block title %} CLIENTES | EDITAR {% endblock %}

{% block content %}


<div class="container d-flex justify-content-center mt-3 mb-5">
    <div class="card shadow-lg p-4" style="width: 100%; max-width: 500px;">
        <div class="card-header text-center">
            <h3 class="text-dark">
                Actualización de Cliente
            </h3>
        </div>
        <div class="card-body">
            <form action="{{ url_for('cliente.edit',id=cliente.id) }}" method="POST">
                <div class="mb-3">
                    <label for="nombre" class="form-label"><i class="bi bi-person-lines-fill me-2"></i>Nombre</label>
                    <input type="text" class="form-control" name="nombre" value="{{cliente.nombre}}" required>
                </div>
                <div class="mb-3">
                    <label for="username" class="form-label"><i class="bi bi-envelope-at me-2"></i>Correo electrónico</label>
                    <input type="text" class="form-control" name="email" value="{{cliente.email}}" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label"><i class="bi bi-telephone-fill me-2" ></i>Telefono</label>
                    <input type="number" class="form-control" name="telefono" value="{{cliente.telefono}}" required>
                </div>

                <!-- Botón de Guardar -->
                <div class="text-center mt-4 mb-3">
                    <button type="submit" class="btn btn-primary btn-lg w-100">
                        <i class="bi bi-check-circle-fill me-2"></i>Actualizar Cliente
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/clientes/index.html
{% extends 'base.html' %}

{% block title %} CLIENTES {% endblock %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-4 mt-4">
        <h2 class="fw-bold text-dark">
            <i class="bi bi-journal-text me-2"></i>Lista de Clientes
        </h2>
        <a href="{{ url_for('cliente.create') }}" class="btn btn-success ">
            <i class="bi bi-plus-circle me-1"></i> Nuevo Cliente
        </a>
    </div>

<table class="table table-hover align-middle shadow-sm rounded overflow-hidden">
    <thead class="table-dark border-1">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Email</th>
            <th>Telefono</th>
            <th></th>
        </tr>
    </thead>
    <tbody class="border-1">
        {% for item in clientes %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.nombre}}</td>
            <td>{{item.email}}</td>
            <td>{{item.telefono}}</td>

            <td class="text-center">
                <a href="{{url_for('cliente.edit',id=item.id)}}" class="btn btn-sm btn-warning me-4" title="Editar">
                    <i class="bi bi-pencil-square"></i>
                </a>
                <a href="{{url_for('cliente.delete',id=item.id)}}" class="btn btn-sm btn-danger " title="Eliminar"
                    onclick="return confirm('¿Estás seguro de eliminar este cliente?');">
                    <i class="bi bi-trash-fill"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>



{% endblock %}